# Generated by Django 6.0.2 on 2026-03-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('discount_type', models.CharField(choices=[('flex', 'Aniq summa'), ('percent', 'Foizli')], max_length=10)),
                ('discount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['id'], 'verbose_name': "O'quvchi", 'verbose_name_plural': "O'quvchilar"},
        ),
        migrations.AddField(
            model_name='students',
            name='Courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='main.course'),
        ),
    ]
